SECONDAR_GROUP = {
                  'VALIDATION_EMAIL':'Group_Comm_EmailValidation',
                  }

GROUP_MENU_PREFIX = 'group_menu_'
TEMPLATE_PARAM_USER_NOT_LOGGED_IN = 'NotDefined'
LOGGER_USER = 'LOGGER_UserSystem'
LOGGER_MENU = ''
SESSION_MESSAGE = 'UserMessages'
SESSION_USER_EXPIRY_TIME = 5*60*1000
CACHE_TIME_FOR_GROUP_MENU = 24*60*60